# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: ATD-Techknowledge
description: "Taking Advantage of Open Source in Your Learning Projects"
keywords: "free, ATD, Techknowledge, open source, learning, education, training"

# Site settings
url: http://crichID.github.io
baseurl: "/ATD-Techknowledge"
# baseurl: ""

# Author settings
author:
  name      : Cynthia Rich
  job       : Trainer
  bio       : "Trainer and Open Source Learning Evangelist."
  thumb     : /images/author.jpg
  email     : crichID@github.com
  url       : http://crichID.github.io
  github    : http://github.com/crichID
  twitter   : http://twitter.com/cynthiarich07
  linkedin  : https://www.linkedin.com/in/crichnc

# google_analytics: UA-52446115-1
repo: http://github.com/crichID/ATD-Techknowledge

# comments
disqus_shortname: ""
