# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "/ATD-Techknowledge/" # the subpath of your site, e.g. /blog/
url: "http://crichID.github.io" # the base hostname & protocol for your site

# User settings
username: Taking Advantage of Open Source in Your Learning Projects
user_description: Open Source Learning Evangelist
user_title: ATD techknowledge
email: crichID@github.com
twitter_username: cynthiarich07
github_username:  crichID

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
